# Site settings
title: 
header-img: img/home-bg.png
email: ritarojas@mac.com
copyright_name: RMSullivan
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: rmsully
github_username:  RMSullivan
learn_profile: RMSullivan
email_username: ritarojas@mac.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
